from enum import Enum

class RowCategories(Enum):
    AUFTRAGSKONTO = "AUFTRAGSKONTO"
    BUCHUNGSTAG = "BUCHUNGSTAG"
    VALUTADATUM = "VALUTADATUM"
    BUCHUNGSTEXT = "BUCHUNGSTEXT"
    VERWENDUNGSZWECK = "VERWENDUNGSZWECK"
    BEGUENSTIGTER_ZAHLUNGSPFLICHTIGER = "BEGUENSTIGTER_ZAHLUNGSPFLICHTIGER"
    KONTONUMMER = "KONTONUMMER"
    BLZ = "BLZ"
    BETRAG = "BETRAG"
    WAEHRUNG = "WAEHRUNG"
    INFO = "INFO"